# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cppBuildInterface <- function(x, y, catCols, numRows, numColumns, ntree, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, seed, nthread, verbose, middleSplit) {
    .Call('hte_rcpp_cppBuildInterface', PACKAGE = 'hte', x, y, catCols, numRows, numColumns, ntree, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, seed, nthread, verbose, middleSplit)
}

rcpp_cppPredictInterface <- function(forest, x) {
    .Call('hte_rcpp_cppPredictInterface', PACKAGE = 'hte', forest, x)
}

rcpp_OBBPredictInterface <- function(forest) {
    .Call('hte_rcpp_OBBPredictInterface', PACKAGE = 'hte', forest)
}

rcpp_AddTreeInterface <- function(forest, ntree) {
    invisible(.Call('hte_rcpp_AddTreeInterface', PACKAGE = 'hte', forest, ntree))
}

rcpp_selectBestFeature <- function(x, y, featureList, sampleIndex, nodesize, splitrule, categoricalFeatureCols) {
    .Call('hte_rcpp_selectBestFeature', PACKAGE = 'hte', x, y, featureList, sampleIndex, nodesize, splitrule, categoricalFeatureCols)
}

